### ISSUE TITLE
Nome do projeto

### ISSUE THREAD

**Issue by thiagommedeiros** [mundipagg/mercurio-checkout#29]
Nosso squad acredita que `mercurio-checkout` não é um nome adequado para o projeto. O nome `mercurio` foi dado ao nosso squad e é um nome apenas para uso interno aqui na Pagar.me.

Chegou a hora de fazermos um brainstorm! Então convocamos todo mundo para comentar nessa issue sugerindo um nome legal para o projeto. Depois disso podemos fazer uma votação para escolher o nome final.

Se você tem uma sugestão comente aqui, toda ideia é bem vinda =)

**Comment by thiagommedeiros** [comment]
Sugestão: `easy-checkout`

**Comment by vcapretz** [comment]
passenger

tem relação com o uso de pilot no projeto da dash

**Comment by thiagommedeiros** [comment]
Sugestão do @marcusflavius: `open-checkout`

**Comment by fernando-barbosa** [comment]
`Heimdall`

Na mitologia nórdica, Heimdallr, ou Heimdall é um deus, com a missão de guardar a ponte Bifrost - um arco-íris ligando o céu à Terra.

**Comment by thiagommedeiros** [comment]
Abrimos votação no Workplace e o nome escolhido foi **artis** =))

Agora o @augusto-jm-amaral vai abrir um PR alterando o nome do projeto.
